secrets:
  jwt:
    file: ./authelia/secrets/jwt
  encryption_key:
    file: ./authelia/secrets/encryption_key
  smtp:
    file: ./authelia/secrets/smtp
  session:
    file: ./authelia/secrets/session

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=985
      - TZ=America/New_York
      - URL=dillonjason.dev
      - SUBDOMAINS=apollo,code-server
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
    restart: unless-stopped
  authelia:
    image: authelia/authelia
    container_name: authelia
    secrets:
      - jwt
      - smtp
      - encryption_key
      - session
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/jwt
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/encryption_key
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/smtp
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session
      - TZ=America/New_York
      - UID=1000
      - GID=985
    volumes:
      - ./authelia/config:/config
    restart: unless-stopped
  homer:
    image: b4bz/homer:latest
    volumes:
      - ./homer/assets:/www/assets
    ports:
      - 8080:8080
    environment:
      - UID=1000
      - GID=985
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user: uid:gid
    # network_mode: "bridge"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /mnt/Media/media:/media
    restart: "unless-stopped"
    environment:
      - TZ=America/New_York
      - UID=1000
      - GID=985
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    volumes:
      - ./code-server/config:/home/coder/.config
      - /home/dillon/Projects:/home/coder/project
    environment:
      - UID=1000
      - GID=985
      - DOCKER_USER=$USER
      - TZ=America/New_York
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    restart: "unless-stopped"
    volumes:
      - ./transmission/data:/data
    cap_add:
      - NET_ADMIN
    env_file:
      - ./transmission/.env
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis/data:/data
    restart: unless-stopped
    environment:
      - TZ=America/New_York
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=985
      - TZ=America/New_York
      - AUTO_UPDATE=true
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=985
      - TZ=America/New_York
    volumes:
      - ./sonarr/config:/config
      - /mnt/Media:/data
    restart: unless-stopped
    ports:
      - 8989:8989
