services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=985
      - TZ=America/New_York
      - URL=dillonjason.dev
      - SUBDOMAINS=apollo,
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
    restart: unless-stopped
  homer:
    image: b4bz/homer:latest
    volumes: 
      - ./homer/assets:/www/assets
    ports:
      - 8080:8080
    environment:
      - UID=1000
      - GID=985