services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=985
      - TZ=America/New_York
      - URL=dillonjason.dev
      - SUBDOMAINS=apollo,code-server
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
    restart: unless-stopped
  authelia:
    image: authelia/authelia
    container_name: authelia
    environment:
      - TZ=America/New_York
      - UID=1000
      - GID=985
    volumes:
      - ./authelia/config:/config
    restart: unless-stopped
  homer:
    image: b4bz/homer:latest
    volumes: 
      - ./homer/assets:/www/assets
    ports:
      - 8080:8080
    environment:
      - UID=1000
      - GID=985
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user: uid:gid
    # network_mode: "bridge"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /mnt/Media:/media
    restart: "unless-stopped"
    environment:
      - UID=1000
      - GID=985
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    volumes:
      - ./code-server/config:/home/coder/.config
      - /home/dillon/Projects:/home/coder/project
    environment:
      - UID=1000
      - GID=985
      - DOCKER_USER=$USER
