---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Demo dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Demo !"
  icon: "fa fa-grin"
  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links: []

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Code Server"
        logo: "assets/tools/sample.png"
        subtitle: "VSCode available anywhere"
        tag: "app"
        url: "https://code-server.dillonjason.dev/"
        target: "_blank"
      - name: "Transmission"
        logo: "assets/tools/sample.png"
        subtitle: "Check on them torrents"
        tag: "app"
        url: "https://apollo.dillonjason.dev/transmission"
        target: "_blank"
      - name: "Jellyfin"
        logo: "assets/tools/sample.png"
        subtitle: "Watch something?"
        tag: "app"
        url: "https://apollo.dillonjason.dev/jellyfin"
        target: "_blank"
  - name: "Services"
    icon: "fas fa-cloud"
    items:
      - name: "Jackett"
        logo: "assets/tools/sample.png"
        subtitle: ""
        tag: "app"
        url: "https://apollo.dillonjason.dev/jackett"
        target: "_blank"
  - name: "Downloads"
    icon: "fas fa-cloud"
    items:
      - name: "Sonarr"
        logo: "assets/tools/sample.png"
        subtitle: "Search for TV shows"
        tag: "app"
        url: "https://apollo.dillonjason.dev/sonarr"
        target: "_blank"
