---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Apollo"
subtitle: "Dashboard"
logo: "assets/icons/icon-any.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#406344"
    highlight-secondary: "#4b7550"
    highlight-hover: "#5b8c61"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#406344"
    highlight-secondary: "#4b7550"
    highlight-hover: "#5b8c61"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links: []

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Media"
    icon: "fas fa-play"
    items:
      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.png"
        subtitle: "Watch something?"
        tag: "app"
        url: "https://apollo.dillonjason.dev/jellyfin"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/tools/sonarr.png"
        subtitle: "Search for TV shows"
        tag: "download"
        url: "https://apollo.dillonjason.dev/sonarr"
        target: "_blank"
      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        subtitle: "Search for moves"
        tag: "download"
        url: "https://apollo.dillonjason.dev/radarr"
        target: "_blank"
  - name: "Tools"
    icon: "fas fa-laptop-code"
    items:
      - name: "Code Server"
        logo: "assets/tools/vscode.png"
        subtitle: "VSCode available anywhere"
        tag: "tool"
        url: "https://code-server.dillonjason.dev/"
        target: "_blank"
  - name: "Services"
    icon: "fas fa-cogs"
    items:
      - name: "Transmission"
        logo: "assets/tools/transmission.png"
        subtitle: "Check on them torrents"
        tag: "torrent"
        url: "https://apollo.dillonjason.dev/transmission"
        target: "_blank"
      - name: "Jackett"
        logo: "assets/tools/jackett.png"
        subtitle: "Torrent indexer"
        tag: "torrent"
        url: "https://apollo.dillonjason.dev/jackett"
        target: "_blank"
      - name: "Prometheus"
        logo: "assets/tools/prometheus.webp"
        subtitle: "Monitor resources"
        tag: "monitoring"
        url: "https://prometheus.dillonjason.dev"
        target: "_blank"
  - name: "Server"
    icon: "fas fa-server"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Server status overview"
        tag: "monitoring"
        url: "https://apollo.dillonjason.dev/grafana"
        target: "_blank"
      - name: "Authelia"
        logo: "assets/tools/authelia.png"
        subtitle: "Authentication config"
        tag: "tool"
        url: "https://code-server.dillonjason.dev/?folder=/home/coder/home-server/authelia"
        target: "_blank"
      - name: "Portainer"
        logo: "assets/tools/portainer.webp"
        subtitle: "Manager docker images"
        tag: "tool"
        url: "https://apollo.dillonjason.dev/portainer"
        target: "_blank"
